syntax = "proto3";

package step_perf_ir;

message DataType {
  oneof type {
    F16 f16 = 1; // Tile f16
    F32 f32 = 2; // Tile f32
    MultiHot multi_hot = 3;
    Index index = 4;
    Buffer buffer = 5; // Tile buffer
    ScalarU64 scalar_u64 = 6; // Scalar u64
    ScalarBool scalar_bool = 7; // Scalar bool
    U64 u64 = 8; // Scalar u64
    Bool bool = 9; // Scalar bool
  }
}

message Buffer {
  oneof type {
    F16 f16 = 1; // Tile f16
    F32 f32 = 2; // Tile f32
  }
}
message ScalarU64 {}
message ScalarBool {}
message U64 {}
message Bool {}
message F16 {}
message F32 {}
message MultiHot {}
message Index {}