syntax = "proto3";

package step_perf_ir;

message DataType {
  oneof type {
    F16 f16 = 1; // Tile f16
    F32 f32 = 2; // Tile f32
    MultiHot multi_hot = 3;
    Index index = 4;
    Buffer buffer = 5;          // Tile buffer
    ScalarU64 scalar_u64 = 6;   // Scalar u64
    ScalarI64 scalar_i64 = 7;   // Scalar i64
    ScalarBool scalar_bool = 8; // Scalar bool
    U64 u64 = 9;                // Tile u64
    I64 i64 = 10;               // Tile i64
    Bool bool = 11;             // Tile bool
  }
}

message Buffer {
  oneof type {
    F16 f16 = 1; // Tile f16
    F32 f32 = 2; // Tile f32
  }
}
message ScalarU64 {}
message ScalarI64 {}
message ScalarBool {}

message U64 { // Tile u64
  oneof row_size {
    uint32 row_static = 1;
    string row_dynamic = 2;
  }
  oneof col_size {
    uint32 col_static = 3;
    string col_dynamic = 4;
  }
}

message I64 { // Tile i64
  oneof row_size {
    uint32 row_static = 1;
    string row_dynamic = 2;
  }
  oneof col_size {
    uint32 col_static = 3;
    string col_dynamic = 4;
  }
}

message Bool { // Tile bool
  oneof row_size {
    uint32 row_static = 1;
    string row_dynamic = 2;
  }
  oneof col_size {
    uint32 col_static = 3;
    string col_dynamic = 4;
  }
}

message F16 { // Tile f16
  oneof row_size {
    uint32 row_static = 1;
    string row_dynamic = 2;
  }
  oneof col_size {
    uint32 col_static = 3;
    string col_dynamic = 4;
  }
}
message F32 { // Tile f32
  oneof row_size {
    uint32 row_static = 1;
    string row_dynamic = 2;
  }
  oneof col_size {
    uint32 col_static = 3;
    string col_dynamic = 4;
  }
}
message MultiHot { uint32 width = 1; }
message Index { uint32 width = 1; }