syntax = "proto3";

package step_perf_ir;

import "ops.proto";

message Phase {
  uint32 group_id = 1;
  string name = 2;
}

message ProgramGraph {
  // optional string name = 1;
  string name = 1;
  repeated Operation operators = 2;
  repeated Phase phases = 3;

  // Reserved for additional metadata.
  reserved 4 to 10;

  // repeated RefStream ref_streams = 11;
  // repeated CrdStream crd_streams = 12;
  // repeated ValStream val_streams = 13;
  // repeated RepSigStream repsig_streams = 14;
}
